services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - app-network

  node:
    build: ./node
    container_name: node
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "start"]
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: f6ad6af5ffb811c59fa86b990eba6331
      MYSQL_DATABASE: nodedb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: